Stage 1
Skazin/TeachMeSkills pull request #11
Opened 2021-02-28 11:56 UTC by Skazin

2021-02-28 14:06 UTC, GlebLitvinov requested changes

2021-02-28 14:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Main.java
> +                if (o1.getPrice() - o2.getPrice() >= 0) return 1;
just do return o1.getPrice() - o2.getPrice() =)

2021-02-28 14:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Main.java
> +        Set<Product> listA = new TreeSet<>(c);
rename it to productsSet

2021-02-28 14:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +        if (productList.contains(product)) {
contains is using equals method to determine if there is an object with given value in the list, so you should add equals method to the Product class to make it work correctly

2021-02-28 14:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +        productList.removeIf(product -> product.getId() == id);
good

2021-02-28 14:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +    }
this is a working solution,  but it seems like an overkill to me
what you could do is:

boolean found = false;
for (Product product : productList) {
 if (product.getId().equals(editedProduct).getId()) {
  found = true;
  product.setName(editedProduct.getName());
  //set type
 // set price
}
if (!found) throw ...

2021-02-28 15:33 UTC, Skazin commented on HomeWorks/src/Market/Main.java
> +                if (o1.getPrice() - o2.getPrice() >= 0) return 1;
if I do this, comparator will not add products if they have equal prices, that's why I override it like this, cos' I can't find other solution

2021-03-01 11:03 UTC, GlebLitvinov commented on HomeWorks/src/Market/Main.java
> +                if (o1.getPrice() - o2.getPrice() >= 0) return 1;
got it

2021-03-01 11:04 UTC, GlebLitvinov commented on HomeWorks/src/Market/Main.java
> +                if (o1.getPrice() - o2.getPrice() >= 0) return 1;
you don't have to use set collection to sort Products, though

2021-03-01 11:07 UTC, GlebLitvinov requested changes

2021-03-01 11:07 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> -            mapList.put(product.getId(), product);
now you don't need mapList and can remove it

2021-03-01 11:07 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +    public List<String> priceSort(List<Product> list) {
it seems like you don't need to pass list param, since you have access to it directly from method
same for orderOfAdditionSort

2021-03-01 11:07 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +        Comparator<Product> c = new Comparator<Product>() {
you don't have to create comparator every time you call this method. You can make it a global variable and initialize in constructor

2021-03-02 15:06 UTC, GlebLitvinov reviewed
get rid of calling listOfProducts method for no reason, other things are good

2021-03-02 15:06 UTC, GlebLitvinov commented on HomeWorks/src/Market/Market.java
> +        String[] arr = new String[listOfProducts().size()];
every time you call listOfProducts() you create new list. So if you only need size you can call productList.size()

2021-03-13 15:23 UTC, merged